"""
Team name aliases: maps abbreviations and common short names to canonical full names.
Also tracks which sport each team belongs to.
"""

# Format: "ALIAS": ("Canonical Name", "SPORT")
TEAM_ALIASES: dict[str, tuple[str, str]] = {
    # ── NBA ──────────────────────────────────────────────────────────────────
    "ATL": ("Atlanta Hawks", "NBA"),
    "BOS": ("Boston Celtics", "NBA"),
    "BKN": ("Brooklyn Nets", "NBA"),
    "CHA": ("Charlotte Hornets", "NBA"),
    "CHI": ("Chicago Bulls", "NBA"),
    "CLE": ("Cleveland Cavaliers", "NBA"),
    "DAL": ("Dallas Mavericks", "NBA"),
    "DEN": ("Denver Nuggets", "NBA"),
    "DET": ("Detroit Pistons", "NBA"),
    "GSW": ("Golden State Warriors", "NBA"),
    "HOU": ("Houston Rockets", "NBA"),
    "IND": ("Indiana Pacers", "NBA"),
    "LAC": ("Los Angeles Clippers", "NBA"),
    "LAL": ("Los Angeles Lakers", "NBA"),
    "MEM": ("Memphis Grizzlies", "NBA"),
    "MIA": ("Miami Heat", "NBA"),
    "MIL": ("Milwaukee Bucks", "NBA"),
    "MIN": ("Minnesota Timberwolves", "NBA"),
    "NOP": ("New Orleans Pelicans", "NBA"),
    "NYK": ("New York Knicks", "NBA"),
    "OKC": ("Oklahoma City Thunder", "NBA"),
    "ORL": ("Orlando Magic", "NBA"),
    "PHI": ("Philadelphia 76ers", "NBA"),
    "PHX": ("Phoenix Suns", "NBA"),
    "POR": ("Portland Trail Blazers", "NBA"),
    "SAC": ("Sacramento Kings", "NBA"),
    "SAS": ("San Antonio Spurs", "NBA"),
    "TOR": ("Toronto Raptors", "NBA"),
    "UTA": ("Utah Jazz", "NBA"),
    "WAS": ("Washington Wizards", "NBA"),
    # common alternates
    "GS": ("Golden State Warriors", "NBA"),
    "NO": ("New Orleans Pelicans", "NBA"),
    "NY": ("New York Knicks", "NBA"),
    "SA": ("San Antonio Spurs", "NBA"),
    "OKC THUNDER": ("Oklahoma City Thunder", "NBA"),
    "LAKERS": ("Los Angeles Lakers", "NBA"),
    "CELTICS": ("Boston Celtics", "NBA"),
    "WARRIORS": ("Golden State Warriors", "NBA"),
    "HEAT": ("Miami Heat", "NBA"),
    "BUCKS": ("Milwaukee Bucks", "NBA"),
    "SUNS": ("Phoenix Suns", "NBA"),
    "NETS": ("Brooklyn Nets", "NBA"),
    "KNICKS": ("New York Knicks", "NBA"),
    "NUGGETS": ("Denver Nuggets", "NBA"),
    "CLIPPERS": ("Los Angeles Clippers", "NBA"),
    "MAVERICKS": ("Dallas Mavericks", "NBA"),
    "MAVS": ("Dallas Mavericks", "NBA"),

    # ── MLB ──────────────────────────────────────────────────────────────────
    "ARI": ("Arizona Diamondbacks", "MLB"),
    "ATL BRAVES": ("Atlanta Braves", "MLB"),
    "BAL": ("Baltimore Orioles", "MLB"),
    "CHC": ("Chicago Cubs", "MLB"),
    "CIN": ("Cincinnati Reds", "MLB"),
    "CLE GUARDIANS": ("Cleveland Guardians", "MLB"),
    "COL": ("Colorado Rockies", "MLB"),
    "DET TIGERS": ("Detroit Tigers", "MLB"),
    "HOU ASTROS": ("Houston Astros", "MLB"),
    "KC ROYALS": ("Kansas City Royals", "MLB"),
    "LAD": ("Los Angeles Dodgers", "MLB"),
    "MIA MARLINS": ("Miami Marlins", "MLB"),
    "MIL BREWERS": ("Milwaukee Brewers", "MLB"),
    "MIN TWINS": ("Minnesota Twins", "MLB"),
    "NYM": ("New York Mets", "MLB"),
    "NYY": ("New York Yankees", "MLB"),
    "OAK": ("Oakland Athletics", "MLB"),
    "PHI PHILLIES": ("Philadelphia Phillies", "MLB"),
    "PIT": ("Pittsburgh Pirates", "MLB"),
    "SD": ("San Diego Padres", "MLB"),
    "SEA": ("Seattle Mariners", "MLB"),
    "SF GIANTS": ("San Francisco Giants", "MLB"),
    "STL": ("St. Louis Cardinals", "MLB"),
    "TB": ("Tampa Bay Rays", "MLB"),
    "TEX": ("Texas Rangers", "MLB"),
    "TOR JAYS": ("Toronto Blue Jays", "MLB"),
    "WSH": ("Washington Nationals", "MLB"),
    "CWS": ("Chicago White Sox", "MLB"),
    # common full names
    "YANKEES": ("New York Yankees", "MLB"),
    "DODGERS": ("Los Angeles Dodgers", "MLB"),
    "RED SOX": ("Boston Red Sox", "MLB"),
    "METS": ("New York Mets", "MLB"),
    "CUBS": ("Chicago Cubs", "MLB"),
    "ASTROS": ("Houston Astros", "MLB"),
    "BRAVES": ("Atlanta Braves", "MLB"),
    "PHILLIES": ("Philadelphia Phillies", "MLB"),
    "PADRES": ("San Diego Padres", "MLB"),
    "GIANTS": ("San Francisco Giants", "MLB"),
    "CARDINALS": ("St. Louis Cardinals", "MLB"),
    "RANGERS": ("Texas Rangers", "MLB"),
    "RAYS": ("Tampa Bay Rays", "MLB"),
    "MARINERS": ("Seattle Mariners", "MLB"),
    "TWINS": ("Minnesota Twins", "MLB"),
    "PIRATES": ("Pittsburgh Pirates", "MLB"),
    "ROYALS": ("Kansas City Royals", "MLB"),
    "ROCKIES": ("Colorado Rockies", "MLB"),
    "BREWERS": ("Milwaukee Brewers", "MLB"),
    "TIGERS": ("Detroit Tigers", "MLB"),
    "ORIOLES": ("Baltimore Orioles", "MLB"),
    "GUARDIANS": ("Cleveland Guardians", "MLB"),
    "ATHLETICS": ("Oakland Athletics", "MLB"),
    "NATIONALS": ("Washington Nationals", "MLB"),
    "MARLINS": ("Miami Marlins", "MLB"),
    "REDS": ("Cincinnati Reds", "MLB"),
    "D-BACKS": ("Arizona Diamondbacks", "MLB"),
    "DIAMONDBACKS": ("Arizona Diamondbacks", "MLB"),
    "BLUE JAYS": ("Toronto Blue Jays", "MLB"),
    "WHITE SOX": ("Chicago White Sox", "MLB"),

    # ── NFL ──────────────────────────────────────────────────────────────────
    "ARI CARDINALS": ("Arizona Cardinals", "NFL"),
    "ATL FALCONS": ("Atlanta Falcons", "NFL"),
    "BAL RAVENS": ("Baltimore Ravens", "NFL"),
    "BUF": ("Buffalo Bills", "NFL"),
    "CAR": ("Carolina Panthers", "NFL"),
    "CHI BEARS": ("Chicago Bears", "NFL"),
    "CIN BENGALS": ("Cincinnati Bengals", "NFL"),
    "CLE BROWNS": ("Cleveland Browns", "NFL"),
    "DAL COWBOYS": ("Dallas Cowboys", "NFL"),
    "DEN BRONCOS": ("Denver Broncos", "NFL"),
    "DET LIONS": ("Detroit Lions", "NFL"),
    "GB": ("Green Bay Packers", "NFL"),
    "HOU TEXANS": ("Houston Texans", "NFL"),
    "IND COLTS": ("Indianapolis Colts", "NFL"),
    "JAX": ("Jacksonville Jaguars", "NFL"),
    "KC": ("Kansas City Chiefs", "NFL"),
    "LAC CHARGERS": ("Los Angeles Chargers", "NFL"),
    "LAR": ("Los Angeles Rams", "NFL"),
    "LV": ("Las Vegas Raiders", "NFL"),
    "MIA DOLPHINS": ("Miami Dolphins", "NFL"),
    "MIN VIKINGS": ("Minnesota Vikings", "NFL"),
    "NE": ("New England Patriots", "NFL"),
    "NO SAINTS": ("New Orleans Saints", "NFL"),
    "NYG": ("New York Giants", "NFL"),
    "NYJ": ("New York Jets", "NFL"),
    "PHI EAGLES": ("Philadelphia Eagles", "NFL"),
    "PIT STEELERS": ("Pittsburgh Steelers", "NFL"),
    "SEA SEAHAWKS": ("Seattle Seahawks", "NFL"),
    "SF": ("San Francisco 49ers", "NFL"),
    "TB BUCCANEERS": ("Tampa Bay Buccaneers", "NFL"),
    "TEN": ("Tennessee Titans", "NFL"),
    "WAS COMMANDERS": ("Washington Commanders", "NFL"),
    # common names
    "CHIEFS": ("Kansas City Chiefs", "NFL"),
    "PATRIOTS": ("New England Patriots", "NFL"),
    "BILLS": ("Buffalo Bills", "NFL"),
    "49ERS": ("San Francisco 49ers", "NFL"),
    "COWBOYS": ("Dallas Cowboys", "NFL"),
    "EAGLES": ("Philadelphia Eagles", "NFL"),
    "RAVENS": ("Baltimore Ravens", "NFL"),
    "BENGALS": ("Cincinnati Bengals", "NFL"),
    "RAMS": ("Los Angeles Rams", "NFL"),
    "PACKERS": ("Green Bay Packers", "NFL"),
    "STEELERS": ("Pittsburgh Steelers", "NFL"),
    "BEARS": ("Chicago Bears", "NFL"),
    "GIANTS": ("New York Giants", "NFL"),
    "JETS": ("New York Jets", "NFL"),
    "RAIDERS": ("Las Vegas Raiders", "NFL"),
    "CHARGERS": ("Los Angeles Chargers", "NFL"),
    "BRONCOS": ("Denver Broncos", "NFL"),
    "SEAHAWKS": ("Seattle Seahawks", "NFL"),
    "VIKINGS": ("Minnesota Vikings", "NFL"),
    "SAINTS": ("New Orleans Saints", "NFL"),
    "FALCONS": ("Atlanta Falcons", "NFL"),
    "LIONS": ("Detroit Lions", "NFL"),
    "BUCCANEERS": ("Tampa Bay Buccaneers", "NFL"),
    "BUCS": ("Tampa Bay Buccaneers", "NFL"),
    "DOLPHINS": ("Miami Dolphins", "NFL"),
    "COLTS": ("Indianapolis Colts", "NFL"),
    "TITANS": ("Tennessee Titans", "NFL"),
    "JAGUARS": ("Jacksonville Jaguars", "NFL"),
    "PANTHERS": ("Carolina Panthers", "NFL"),
    "TEXANS": ("Houston Texans", "NFL"),
    "BROWNS": ("Cleveland Browns", "NFL"),
    "CARDINALS": ("Arizona Cardinals", "NFL"),
    "COMMANDERS": ("Washington Commanders", "NFL"),

    # ── NHL ──────────────────────────────────────────────────────────────────
    "ANA": ("Anaheim Ducks", "NHL"),
    "ARI COYOTES": ("Arizona Coyotes", "NHL"),
    "BOS BRUINS": ("Boston Bruins", "NHL"),
    "BUF SABRES": ("Buffalo Sabres", "NHL"),
    "CGY": ("Calgary Flames", "NHL"),
    "CAR HURRICANES": ("Carolina Hurricanes", "NHL"),
    "CHI HAWKS": ("Chicago Blackhawks", "NHL"),
    "COL AVALANCHE": ("Colorado Avalanche", "NHL"),
    "CBJ": ("Columbus Blue Jackets", "NHL"),
    "DAL STARS": ("Dallas Stars", "NHL"),
    "DET RED WINGS": ("Detroit Red Wings", "NHL"),
    "EDM": ("Edmonton Oilers", "NHL"),
    "FLA": ("Florida Panthers", "NHL"),
    "LA KINGS": ("Los Angeles Kings", "NHL"),
    "MIN WILD": ("Minnesota Wild", "NHL"),
    "MTL": ("Montreal Canadiens", "NHL"),
    "NSH": ("Nashville Predators", "NHL"),
    "NJ": ("New Jersey Devils", "NHL"),
    "NYI": ("New York Islanders", "NHL"),
    "NYR": ("New York Rangers", "NHL"),
    "OTT": ("Ottawa Senators", "NHL"),
    "PHI FLYERS": ("Philadelphia Flyers", "NHL"),
    "PIT PENGUINS": ("Pittsburgh Penguins", "NHL"),
    "SEA KRAKEN": ("Seattle Kraken", "NHL"),
    "SJS": ("San Jose Sharks", "NHL"),
    "STL BLUES": ("St. Louis Blues", "NHL"),
    "TBL": ("Tampa Bay Lightning", "NHL"),
    "TOR MAPLE LEAFS": ("Toronto Maple Leafs", "NHL"),
    "VAN": ("Vancouver Canucks", "NHL"),
    "VGK": ("Vegas Golden Knights", "NHL"),
    "WSH CAPITALS": ("Washington Capitals", "NHL"),
    "WPG": ("Winnipeg Jets", "NHL"),
    # common names
    "BRUINS": ("Boston Bruins", "NHL"),
    "RANGERS": ("New York Rangers", "NHL"),
    "PENGUINS": ("Pittsburgh Penguins", "NHL"),
    "LIGHTNING": ("Tampa Bay Lightning", "NHL"),
    "GOLDEN KNIGHTS": ("Vegas Golden Knights", "NHL"),
    "OILERS": ("Edmonton Oilers", "NHL"),
    "AVALANCHE": ("Colorado Avalanche", "NHL"),
    "MAPLE LEAFS": ("Toronto Maple Leafs", "NHL"),
    "HURRICANES": ("Carolina Hurricanes", "NHL"),
    "FLAMES": ("Calgary Flames", "NHL"),
    "CANUCKS": ("Vancouver Canucks", "NHL"),
    "BLUES": ("St. Louis Blues", "NHL"),
    "BLACKHAWKS": ("Chicago Blackhawks", "NHL"),
    "ISLANDERS": ("New York Islanders", "NHL"),
    "SABRES": ("Buffalo Sabres", "NHL"),
    "DUCKS": ("Anaheim Ducks", "NHL"),
    "SHARKS": ("San Jose Sharks", "NHL"),
    "STARS": ("Dallas Stars", "NHL"),
    "WILD": ("Minnesota Wild", "NHL"),
    "PREDATORS": ("Nashville Predators", "NHL"),
    "SENATORS": ("Ottawa Senators", "NHL"),
    "CANADIENS": ("Montreal Canadiens", "NHL"),
    "DEVILS": ("New Jersey Devils", "NHL"),
    "FLYERS": ("Philadelphia Flyers", "NHL"),
    "CAPITALS": ("Washington Capitals", "NHL"),
    "JETS": ("Winnipeg Jets", "NHL"),
    "KRAKEN": ("Seattle Kraken", "NHL"),
    "RED WINGS": ("Detroit Red Wings", "NHL"),

    # ── NCAAB common teams ───────────────────────────────────────────────────
    "DUKE": ("Duke Blue Devils", "NCAAB"),
    "UNC": ("North Carolina Tar Heels", "NCAAB"),
    "UK": ("Kentucky Wildcats", "NCAAB"),
    "KU": ("Kansas Jayhawks", "NCAAB"),
    "UCLA": ("UCLA Bruins", "NCAAB"),
    "GONZAGA": ("Gonzaga Bulldogs", "NCAAB"),
    "VILLANOVA": ("Villanova Wildcats", "NCAAB"),

    # ── NCAAF common teams ───────────────────────────────────────────────────
    "BAMA": ("Alabama Crimson Tide", "NCAAF"),
    "OSU": ("Ohio State Buckeyes", "NCAAF"),
    "LSU": ("LSU Tigers", "NCAAF"),
    "UGA": ("Georgia Bulldogs", "NCAAF"),
    "CLEMSON": ("Clemson Tigers", "NCAAF"),
    "ND": ("Notre Dame Fighting Irish", "NCAAF"),
    "NOTRE DAME": ("Notre Dame Fighting Irish", "NCAAF"),
    "MICHIGAN": ("Michigan Wolverines", "NCAAF"),
    "OHIO STATE": ("Ohio State Buckeyes", "NCAAF"),
    "ALABAMA": ("Alabama Crimson Tide", "NCAAF"),
    "GEORGIA": ("Georgia Bulldogs", "NCAAF"),
}

# Build reverse lookup: canonical name (upper) → (canonical, sport)
_CANONICAL_UPPER: dict[str, tuple[str, str]] = {
    v[0].upper(): v for v in TEAM_ALIASES.values()
}


def resolve_team(name: str) -> tuple[str, str, float]:
    """
    Resolve a team name string to (canonical_name, sport, confidence).
    confidence = 1.0 for exact alias match, 0.75 for canonical match,
                 0.6 for fuzzy match, 0.0 if not found.
    """
    from thefuzz import process

    key = name.strip().upper()

    # Exact alias match
    if key in TEAM_ALIASES:
        canonical, sport = TEAM_ALIASES[key]
        return canonical, sport, 1.0

    # Exact canonical name match
    if key in _CANONICAL_UPPER:
        canonical, sport = _CANONICAL_UPPER[key]
        return canonical, sport, 0.75

    # Fuzzy match against all aliases
    all_keys = list(TEAM_ALIASES.keys())
    result = process.extractOne(key, all_keys, score_cutoff=70)
    if result:
        matched_key, score = result[0], result[1]
        canonical, sport = TEAM_ALIASES[matched_key]
        confidence = round(score / 100 * 0.6, 2)
        return canonical, sport, confidence

    return name.strip(), "Unknown", 0.0
